### ISSUE TITLE
admin user

### ISSUE THREAD

**Issue by adam5895** [PeriodFriendlyBristol/period-dignity-app-server#6]
currently a default admin user is created during docker startup.
this will have to be removed and an admin user created manually in production.

currently:
name - 'admin'
password - 'Pa55word'    <---- so secure. no one would ever guess that!

line `python3 server/manage.py shell < server/tools/create_admin.py` in run.sh (the docker CMD) calls the create_admin.py script to create this user in development.

**Comment by cgillions** [comment]
These details are now injected by Ansible during deployment.
